# Generated by Django 3.2.23 on 2023-11-28 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('document', models.FileField(upload_to='uploads/task_docs')),
                ('course', models.CharField(default='Any', max_length=100)),
                ('budget', models.PositiveIntegerField(default=0)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
