# Generated by Django 3.2.23 on 2023-11-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='approval',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='bid_by',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='payment',
            field=models.CharField(default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='submission',
            field=models.FileField(default='Pending', upload_to='uploads/submissions'),
        ),
        migrations.AddField(
            model_name='task',
            name='uploaded_by',
            field=models.IntegerField(default=1),
        ),
    ]
