# Generated by Django 3.2.23 on 2023-11-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/slider')),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('fb_link', models.TextField()),
                ('twitter_link', models.TextField()),
                ('instagram_field', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/team')),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('image', models.ImageField(upload_to='uploads/testimonial')),
                ('status', models.CharField(default='Active', max_length=100)),
            ],
        ),
    ]
