# Generated by Django 3.2.23 on 2023-11-27 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_tutor',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='is_client', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='is_active', max_length=100),
        ),
    ]
